# Copyright 2025 Cowboy AI, LLC.

name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Verify version
      run: |
        cargo_version=$(grep "^version" Cargo.toml | sed -E 's/version = "(.*)"/\1/')
        tag_version=${GITHUB_REF#refs/tags/v}
        if [ "$cargo_version" != "$tag_version" ]; then
          echo "Version mismatch: Cargo.toml has $cargo_version, but tag is v$tag_version"
          exit 1
        fi
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
  
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          See [CHANGELOG.md](https://github.com/thecowboyai/cim-domain-git/blob/main/CHANGELOG.md) for details.